extract = 'total_dyn_inst: (\d+)'
# benchmarks = '../../bril/examples/test/tdce/*.bril'
# benchmarks = '../bril/benchmarks/**/*.bril'
timeout = 200

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.tdce]
pipeline = ["bril2json", "../target/debug/tdce", "bril2json", "brili -p {args}"]

[runs.lvn]
pipeline = ["bril2json", "../target/debug/lvn", "bril2json", "brili -p {args}"]

[runs.lvn_then_tdce]
pipeline = [
    "bril2json",
    "../target/debug/lvn",
    "bril2json",
    "../target/debug/tdce",
    "bril2json",
    "brili -p {args}",
]
