extract = 'total_dyn_inst: (\d+)'
timeout = 200

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.insert-preheader]
pipeline = [
  "bril2json",
  "../target/debug/loop-opt --stage 0",
  "bril2json",
  "brili -p {args}",
]
