extract = 'total_dyn_inst: (\d+)'
timeout = 200

[runs.baseline]
pipeline = ["bril2json", "brili -p {args}"]

[runs.from_ssa]
pipeline = [
  "bril2json",
  "../../../target/debug/ssa --from-ssa",
  "bril2json",
  "brili -p {args}",
]
