set shell := ["/bin/bash", "-c"]
set export

LLVM_SYS_180_PREFIX := `brew --prefix llvm@18`
PATH := LLVM_SYS_180_PREFIX / "bin:" + `echo $PATH`
target_dir := "../target"

setup_and_verify_llvm:
    clang --version
    opt --version

build_pass: setup_and_verify_llvm
    cargo build --package llvm-pass || (cargo clean && cargo build --package llvm-pass)

run_pass file: build_pass
    clang -S -emit-llvm {{file}} -o out.ll
    opt --load-pass-plugin={{target_dir}}/debug/libllvm_pass.dylib --passes=auto-memoize:verbose out.ll -f | llvm-dis > out.new.ll

run_pass_and_code file: (run_pass file)
    clang out.new.ll
    ./a.out
