[package]
name = "bril-lsp"
version.workspace = true
edition.workspace = true
license = "GPL-3.0"

[dependencies]
tokio = { version = "1.43.0", features = [
    "rt-multi-thread",
    "macros",
    "io-std",
] }
tower-lsp = "0.20.0"
brilirs = { git = "https://github.com/sampsyo/bril" }
