name: CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

env:
  CARGO_INCREMENTAL: 1

jobs:
  lesson2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Clone Bril
        run: git clone https://github.com/sampsyo/bril && cd bril && git reset --hard 94764e92585c7133d08ac14cf3c563d1d272434a

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: /bril/bril-txt/pyproject.toml

      - name: Install Flit
        run: pip install flit
      - name: Install Python tools
        run: cd bril/bril-txt ; flit install --symlink

      - name: Install Turnt
        # run: pip install turnt  # Use instead if pip turnt version >= 1.7
        uses: actions/checkout@v4
        with:
          repository: cucapra/turnt
          path: './turnt'
      - name: Install Turnt part 2
        run: cd turnt ; flit install --symlink

      - name: Test build-cfg
        run: make build_cfg \
            ROOT="/home/runner/work/cs6120/cs6120" \
            BRIL="../bril"
  lesson3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Clone Bril
        run: cd .. && git clone https://github.com/sampsyo/bril

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
     
      - name: Install brili
        run: cd ../bril && deno install --global brili.ts 

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: /bril/bril-txt/pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install Python tools
        run: |
          cd ../bril
          uv tool install bril-txt
          uv tool install brench
      
      - name: Test trivial DCE
        run: cd lesson3 && cargo build --package tdce && brench brench.toml
