name: CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

env:
  CARGO_INCREMENTAL: 0

jobs:
  bril_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Integration tests
        run: cargo test -p bril-frontend

      - name: Clone Bril
        run: git clone https://github.com/sampsyo/bril

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: /bril/bril-txt/pyproject.toml

      - name: Install Flit
        run: pip install flit
      - name: Install Python tools
        run: cd bril/bril-txt ; flit install --symlink

      - name: Test correct parsing
        run: |
          cd lesson2
          python3 test/check_equivalence.py "bril-frontend --example print" "../target/debug/examples/print -" \
            ../bril/benchmarks/**/*.bril \
            --exclude ../bril/benchmarks/float/cordic.bril

  lesson2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Clone Bril
        run: git clone https://github.com/sampsyo/bril

      - uses: actions/setup-python@v4
        with:
            python-version: '3.11'
            cache: pip
            cache-dependency-path: /bril/bril-txt/pyproject.toml

      - name: Install Flit
        run: pip install flit
      - name: Install Python tools
        run: cd bril/bril-txt ; flit install --symlink

      - name: Install Turnt
        # run: pip install turnt  # Use instead if pip turnt version >= 1.7
        uses: actions/checkout@v4
        with:
          repository: cucapra/turnt
          path: './turnt'
      - name: Install Turnt part 2
        run: cd turnt ; flit install --symlink

      - name: Test build-cfg
        run: |
          cd lesson2
          python3 test/check_equivalence.py build-cfg "../target/debug/build-cfg --mode passthrough" bril2json \
          ../bril/benchmarks/**/*.bril \
            --exclude ../bril/benchmarks/float/cordic.bril
