[package]
name = "llvm-pass"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
llvm-plugin.workspace = true
either.workspace = true
slotmap.workspace = true
